# Generated by Django 4.0.7 on 2023-01-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
    ]
